### ISSUE TITLE
mising array definition in collect_msrc.ps1

### ISSUE THREAD

**Issue by lkucera** [bitsadmin/wesng#11]
seems that $cves_msrc = @() is missing from collect_msrc.ps1 thus the script returns many errors and only one item...

**Comment by bitsadmin** [comment]
Thanks Lukas. The issue were the incorrect line endings which turned the line you mention into a comment. Now it should work well.

https://github.com/bitsadmin/wesng/blob/master/collector/collect_msrc.ps1#L41
