### ISSUE TITLE
Chardet library missing, no instructions on how to get

### ISSUE THREAD

**Issue by Monte-Christo** [bitsadmin/wesng#14]
Python is apparently not enough to run this on WIn 10:

`> .\wes.py systeminfo.txt > wes-report.txt`
`Traceback (most recent call last):`
`  File "C:\Users\Edgar.Knapp\Downloads\wesng-master\wes.py", line 65, in main
    import chardet`
`ModuleNotFoundError: No module named 'chardet'`  

I tried

`> pip3 install chardet`
`'pip3' is not recognized as an internal or external command, operable program or batch file.`

Some instructions on what to do would be helpful.

**Comment by bitsadmin** [comment]
Hi Monte-Christo, in my experience in most cases you won't need the chardet library as the text file is usually stored in ASCII encoding.

For your issue, pip3.exe is installed in the Scripts folder of your Python3 installation. If you navigate to that folder using cmd.exe or PowerShell and execute the command you mentioned, it should work well.

Nevertheless, good point to add some additional documentation on this. Will leave this issue open to add it to the documentation.

Hope this works!

**Comment by Monte-Christo** [comment]
Hi, 

Thanks for the quick response. My biggest problem was that somehow Python 3.7.2 (py.exe) got installed in c:\Windows, without pip or anything else (Is is part of Visual Studio 2017, 2019, or VS Code?). "where py" returns c:\Windows,and .py files are associated with py.exe.

I had to download Python separately from python.org and set the path manually, then things started to work. But chardet is definitely needed to run wes.py on my laptop.

I hope my experiences help others avoid some of these issues.

**Comment by bitsadmin** [comment]
I see, possibly some Visual Studio extension indeed installed the minimum python without pip. You also seem to get a different error than the one that is being caught. ModuleNotFoundError instead of ImportError. Improved robustness by catching both of them now. Let me know in case it still fails for some reason.
