### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by miguelfaldutti87** [bitsadmin/wesng#17]
Here you have the requested logs:
https://mega.nz/#!wgRCxApA

I've Win10 version 1803, build 17134.619

**Comment by bitsadmin** [comment]
Thanks Miguel. Can you also share the key? Or upload the file to file.io.

It seems that Mega is not ideal as you seem to have to create an account in order to generate a publicly shareable link.

I also updated the wiki referring to file.io instead of mega.nz.

**Comment by miguelfaldutti87** [comment]
https://file.io/DSI3ek

**Comment by bitsadmin** [comment]
Tnx, got it. As you didn't include the output of the `listupdates.vbs` script I assume you don't have any updates pending.

**Comment by miguelfaldutti87** [comment]
That's right. I applied 'til the last patch i saw on Windows Catalog :P

**Comment by bitsadmin** [comment]
Hi Miguel, I just pushed an update for wes.py, including an approach on how to deal with false positives.

https://github.com/bitsadmin/wesng/wiki/Eliminating-false-positives

This will eliminate most of your false positives. There are only two left which I haven't looked at, but I will take a look at them in a bit. For now I will close this issue.
