### ISSUE TITLE
Feature request: packaging of wesng on PyPi

### ISSUE THREAD

**Issue by 2xyo** [bitsadmin/wesng#2]
It would be great to have `wesng` packaged on https://pypi.org/  :)

**Comment by bitsadmin** [comment]
Nice idea! I'm first working on some stability improvements, then I will look at publishing the package at the PyPI repository.

**Comment by bitsadmin** [comment]
Finally got some time to look into this. Thanks @2xyo, for the example setup.py! With some minor modifications I added it to the repository and published it on PyPI: https://pypi.org/project/wesng/.
