### ISSUE TITLE
Native script instead phyton

### ISSUE THREAD

**Issue by beerisgood** [bitsadmin/wesng#40]
Would be good if this can be build within system intern commandline like CMD or Powershell instead of phyton

**Comment by bitsadmin** [comment]
Nice suggestion, that would indeed be useful. Hope someone will be inspired to pick this up :-)

For now as a workaround an option is to compile the script into a binary using PyInstaller:

1. **Install PyInstaller**: `pip install PyInstaller`

2. **Generate the Windows/Linux binary:** `pyinstaller --onefile wes.py`

3. Output file can be found in `./dist`

_Source: https://github.com/bitsadmin/nmappy/blob/master/README.md#pyinstaller_
