### ISSUE TITLE
Superseded patch flag

### ISSUE THREAD

**Issue by jsarkisian** [bitsadmin/wesng#43]
Hello, great work on this! Just curious if there's a way to add an option to not show superseded patches? Sounds like it may help with the false positive issues you have detailed.

**Comment by bitsadmin** [comment]
Thanks for your comment! The script contains logic to filter out superseded patches, however this supersedence is working as well as Microsoft's MSRC feed includes this information in their feed.

See the [Wiki](https://github.com/bitsadmin/wesng/wiki) for more information on this.
