### ISSUE TITLE
[FEATURE REQUEST] Use it as API

### ISSUE THREAD

**Issue by tbhaxor** [bitsadmin/wesng#48]
This project is cool. Have you thought of extending it much further. Creating an API like module that parses the systeminfo file and generates a list of results?

**Comment by bitsadmin** [comment]
Thanks for your comment! And good to see you already figured it out. Probably you found the export to CSV option which makes it possible to subsequently have it parsed by another tool. That should work well in case you want to automate things. Enjoy!
