### ISSUE TITLE
Help with code

### ISSUE THREAD

**Issue by tbhaxor** [bitsadmin/wesng#49]
1. What is difference between filtered and found
https://github.com/bitsadmin/wesng/blob/57d6689e286d1ce0775c8e87f91aa38912409a5d/wes.py#L401

I might require your help until the project is over, please don't close. I will close it myself

**Comment by bitsadmin** [comment]
It has been a while since I developed the code, so by quickly looking at the code I can't identify what the difference is. Quickest way to figure it out will probably be to load the code in a debugger like PyCharm and set a breakpoint to see the differences between the two lists. Hope that helps!

**Comment by bitsadmin** [comment]
Project should be finished by now, issue closed. You can create a new one in case any other questions might arise.
