### ISSUE TITLE
how you generate the definition zip file ?

### ISSUE THREAD

**Issue by themeswordpress** [bitsadmin/wesng#61]
Hey boss, 

At first, i would like to thank you so mush for your great job.

Can you provide us with your code to generate the definition zip file please? 

BR

**Comment by bitsadmin** [comment]
Hi,

Glad to hear the tool is useful to you!

For the collection script, please check the `.ps1` files in the `collector` directory. More details on the collection are available in the **Dataset** section of the [Windows Security Updates for Hackers blog post](https://bitsadm.in/blog/windows-security-updates-for-hackers) at [bitsadm.in](https://bitsadm.in/).

Best, Arris
