### ISSUE TITLE
definitions.zip problems

### ISSUE THREAD

**Issue by sebastienfnt1** [bitsadmin/wesng#62]
Hello,

I believe that the csv file contained in definitions.zip is incomplete
the result of collect_msrc.ps1 seems consistent.

**Comment by bitsadmin** [comment]
Thanks Sebastien for your report!

What information is missing according to you?

Unfortunately we are limited to the data that is provided in the various feeds (MSRC, NVD). In case the information is also missing there, the only option is to manually complement the `.csv` file in the `collector` subdirectory. See also the **Dataset** section of the **Windows Security Updates for Hackers** blog post at [bitsadm.in](https://bitsadm.in/)[1].

In case you found a bug in the collector, please let me know.

Best,
Arris

[1] https://bitsadm.in/blog/windows-security-updates-for-hackers#dataset
