### ISSUE TITLE
Question: definitions.zip

### ISSUE THREAD

**Issue by majidmc2** [bitsadmin/wesng#65]
Hi
Do you update the "**definitions.zip**" file automatically? If yes, could you please send the update code of this file?

**Comment by bitsadmin** [comment]
Hi Majid,

Do you mean the the creation of the definitions itself? The scripts to create the `definitions.zip` file are in the `collector` folder of this repository.

If you are wondering whether I have a fully automated process to create the updated `definitions.zip` file and then automatically upload it to this repository, the answer is no. Whenever I think about it I execute the following PowerShell one-liner the and upload it to GitHub once it is done: `.\collect_msrc.ps1 ; .\collect_nvd.ps1`.

Hope that helps!

Best,
Arris
