### ISSUE TITLE
Add the possibility to generate our own definitions.zip

### ISSUE THREAD

**Issue by Starmania** [bitsadmin/wesng#69]
Hey,

If you can share the script you use, even if it requires a very heavy development environment, some API keys or others things that are just difficult to get

Thanks

**Comment by bitsadmin** [comment]
Hi @Starmania, the PowerShell scripts to generate the `definitions.zip` file are available in the `collector` directory.

For some details on the collector, see the blog post [1]. Also some more details in a similar question [2].

Best,
Arris


[1] https://blog.bitsadmin.com/blog/windows-security-updates-for-hackers#dataset
[2] https://github.com/bitsadmin/wesng/issues/65#issuecomment-1177998326

**Comment by Starmania** [comment]
Thanks, and  I'm so sorry I didn't look it up before....

**Comment by bitsadmin** [comment]
No worries and let me know in case you run into any issues!
