### ISSUE TITLE
Win7_index_out_of_range_error

### ISSUE THREAD

**Issue by olni** [bitsadmin/wesng#9]
..i tried wes.py on a win7 ultimate and got problems maybe you have an idea what is missing?

i already did: pip install chardet and pip install regex

1) 
PS C:\Users\oli7\Downloads\wesng-master> py.exe -V
Python 3.7.2

2) wes.py -u worked fine
3) systeminfo >steminfo.txt  works as well but,

PS C:\Users\oli7\Downloads\wesng-master> .\wes.py .\systeminfo.txt > .\wes-report.txt
result is:

`PS C:\Users\oli7\Downloads\wesng-master> .\wes.py .\systeminfo.txt > .\wes-report.txt
Traceback (most recent call last):
  File "C:\Users\oli7\Downloads\wesng-master\wes.py", line 288, in <module>
    main()
  File "C:\Users\oli7\Downloads\wesng-master\wes.py", line 63, in main
    systeminfo_matches = regex_version.findall(systeminfo)[0]
IndexError: list index out of range
PS C:\Users\oli7\Downloads\wesng-master>`

**Comment by bitsadmin** [comment]
Thanks olni for your report! Can you upload the output of step 3 on pastebin so I can reproduce the issue? Thanks!

**Comment by olni** [comment]
https://pastebin.com/9EPnRtiP

**Comment by bitsadmin** [comment]
LOL, I had tested the tool with English, Dutch and a language from which I thought it was the extreme other end of the spectrum of languages: Chinese, but it turned out that the German language is the one which uses different labels :-)
Anyway, with the input of @filo-man, I made the detection more generic, and the German systeminfo output is now also correctly recognized.

**Comment by olni** [comment]
thx, it's working now. ;-)

Olli 

Am 4. März 2019 21:39:57 MEZ schrieb Arris Huijgen <notifications@github.com>:
>LOL, I had tested the tool with English, Dutch and a language from
>which I thought it was the extreme other end of the spectrum of
>languages: Chinese, but it turned out that the German language is the
>one which uses different labels :-)
>Anyway, with the input of @filo-man, I made the detection more generic,
>and the German systeminfo output is now also correctly recognized.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bitsadmin/wesng/issues/9#issuecomment-469413022

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
